[package]
name = "event_bus_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
thiserror = "2.0.17"
async-broadcast = "0.7"
futures = "0.3"
async-stream = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
